[package]
name = "scheme-to-wasm"
version = "0.1.0"
authors = ["Chriscbr <crybicki98@gmail.com>"]
edition = "2024"

[dependencies]
lexpr = "0.2.3"
im-rc = "15.0.0"
parity-wasm = "0.45"

[dev-dependencies]
serial_test = "3.2.0"
wasmer = "6.0.1"
